# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-06 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverlocation',
            old_name='driver',
            new_name='user',
        ),
    ]
