# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 12:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverorder',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
