# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_driverorder_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverorder',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
