# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-07 05:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0002_auto_20170306_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShadowFaxUpdates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rider_name', models.CharField(blank=True, max_length=200, null=True)),
                ('rider_contact', models.CharField(blank=True, max_length=200, null=True)),
                ('sfx_order_id', models.CharField(max_length=32)),
                ('client_order_id', models.CharField(max_length=32)),
                ('order_status', models.CharField(max_length=32)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
