# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 15:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0003_auto_20170803_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
