# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-16 10:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0004_auto_20170804_2030'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('recorded_time', models.DateTimeField(auto_now_add=True)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.DriverOrder')),
            ],
        ),
        migrations.CreateModel(
            name='OrderEvents',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=200)),
                ('driver_position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='driver.DriverPosition')),
            ],
        ),
    ]
