# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-02 05:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0005_driverposition_orderevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverStat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('no_of_orders', models.IntegerField(default=0)),
                ('km_travels', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
