# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-15 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0006_driverstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='driverposition',
            name='driver',
        ),
        migrations.AddField(
            model_name='driverposition',
            name='driver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='orderevents',
            name='driver',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='driver.DriverOrder'),
            preserve_default=False,
        ),
    ]
