# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-23 08:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0008_drivertrip'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='trip_completed',
            field=models.BooleanField(default=False),
        ),
    ]
