# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 10:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0009_drivertrip_trip_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='drivertrip',
            name='km_traveled',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
