# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0010_auto_20180102_1546'),
        ('driver', '0004_auto_20170804_2030'),
    ]

    operations = [
    ]
