# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 14:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('driver', '0011_driverloginlogout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivertrip',
            name='km_traveled',
        ),
        migrations.AddField(
            model_name='driverorder',
            name='driver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverposition',
            name='driver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driverstat',
            name='driver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='driver_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='km_travelled',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
