# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 11:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20180208_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='km_travelled',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
