# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0012_auto_20180118_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivertrip',
            name='km_traveled',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
    ]
