# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-18 11:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0013_auto_20180118_1557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='driverorder',
            old_name='user',
            new_name='driver_user',
        ),
        migrations.RenameField(
            model_name='driverposition',
            old_name='user',
            new_name='driver_user',
        ),
        migrations.RenameField(
            model_name='driverstat',
            old_name='user',
            new_name='driver_user',
        ),
        migrations.RenameField(
            model_name='drivertrip',
            old_name='user',
            new_name='driver_user',
        ),
        migrations.RenameField(
            model_name='orderevents',
            old_name='driver',
            new_name='driver_order',
        ),
    ]
