# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-06 09:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0011_driverloginlogout'),
        ('driver', '0014_auto_20180118_1717'),
    ]

    operations = [
    ]
