# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 02:19
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_auto_20180118_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverorder',
            name='driver_user',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
