# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-02 06:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0014_driverposition_trip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverposition',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_position', to='driver.DriverTrip'),
        ),
    ]
