# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-02 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0015_auto_20180902_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='drivertrip',
            name='auto_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drivertrip',
            name='status',
            field=models.SmallIntegerField(default=0),
        ),
    ]
