# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-24 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20180124_0927'),
    ]

    operations = [
    ]
