# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0016_auto_20180902_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='driverloginlogout',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
