# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-05 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_googlegeocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleAddressLatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.IntegerField(db_index=True)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
            ],
        ),
    ]
