# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-14 11:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0017_driverloginlogout_store_id'),
        ('driver', '0018_googleaddresslatlng'),
    ]

    operations = [
    ]
