# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-24 10:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('driver', '0019_merge_20180914_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverloginlogout',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='driverposition',
            name='latitude',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='driverposition',
            name='longitude',
            field=models.FloatField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='orderevents',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.DriverOrder'),
        ),
        migrations.AlterField(
            model_name='orderevents',
            name='driver_position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='driver.DriverPosition'),
        ),
        migrations.AlterField(
            model_name='orderevents',
            name='status',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
