# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 07:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20171115_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycustomer',
            name='isnotified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 20, 0, tzinfo=utc)),
        ),
    ]
