# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-04 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20171128_2036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifycustomer',
            old_name='isnotified',
            new_name='is_notified',
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 4, 20, 0, tzinfo=utc)),
        ),
    ]
