# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20171221_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 1, 18, 20, 0, tzinfo=utc)),
        ),
    ]
