# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-29 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180213_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(
                default=datetime.datetime(
                    2018, 1, 29, 20, 0, tzinfo=utc)),
        ),
    ]
