# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-08 12:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20180129_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 8, 20, 0, tzinfo=utc)),
        ),
    ]
