# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 11:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180208_1826'),
        ('inventory', '0008_auto_20180129_1528'),
    ]

    operations = [
    ]
