# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-09 11:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_merge_20180209_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 9, 20, 0, tzinfo=utc)),
        ),
    ]
