# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-12 12:58
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0012_auto_20180905_1512'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('type', models.IntegerField(blank=True, null=True)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('is_done', models.BooleanField(default=False)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 12, 20, 0, tzinfo=utc)),
        ),
    ]
