# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 06:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20180213_1309'),
        ('inventory', '0013_auto_20180209_1647'),
    ]

    operations = [
    ]
