# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-12 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_auto_20180912_1828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventoryrequest',
            old_name='type',
            new_name='store_id',
        ),
    ]
