# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_merge_20180412_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 4, 24, 20, 0, tzinfo=utc)),
        ),
    ]
