# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-06 18:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180424_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 5, 6, 20, 0, tzinfo=utc)),
        ),
    ]
