# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-12 13:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_auto_20180912_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryrequest',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
