# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-04 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20180506_2343'),
        ('inventory', '0010_auto_20180510_1135'),
    ]

    operations = [
    ]
