# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-14 07:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_auto_20180912_1912'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifycustomer',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='notifycustomer',
            name='sku',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 14, 20, 0, tzinfo=utc)),
        ),
    ]
