# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-14 11:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_auto_20180914_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifycustomer',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='notifycustomer',
            name='sku',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='product_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='sku',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
