# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-09 09:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_merge_20180704_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 9, 20, 0, tzinfo=utc)),
        ),
    ]
