# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-14 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180914_1703'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventoryrequest',
            name='is_done',
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='status',
            field=models.SmallIntegerField(default=False),
        ),
    ]
