# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-07-10 06:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_auto_20180709_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 7, 10, 20, 0, tzinfo=utc)),
        ),
    ]
