# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-03 12:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_auto_20180902_1209'),
        ('inventory', '0019_auto_20180710_1207'),
    ]

    operations = [
    ]
