# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-19 11:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180916_0947'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventorylog',
            fields=[
                ('inventorylogid', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('relatedto', models.CharField(blank=True, max_length=255, null=True)),
                ('createdat', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('adminuser', models.CharField(blank=True, max_length=255, null=True)),
                ('revert', models.CharField(blank=True, max_length=255, null=True)),
                ('stockupdatedfrom', models.CharField(blank=True, max_length=255, null=True)),
                ('stockupdatedto', models.CharField(blank=True, max_length=255, null=True)),
                ('store_id', models.CharField(blank=True, max_length=255, null=True)),
                ('type_of_qty', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inventorylog',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='inventoryrequest',
            name='type',
            field=models.SmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 20, 0, tzinfo=utc)),
        ),
    ]
