# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-19 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_auto_20180916_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 19, 20, 0, tzinfo=utc)),
        ),
    ]
