# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_auto_20180914_1157'),
        ('inventory', '0021_auto_20180919_1705'),
    ]

    operations = [
    ]
