# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 09:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_merge_20180919_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryrequest',
            name='gpu',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 9, 20, 20, 0, tzinfo=utc)),
        ),
    ]
