# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 11:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_auto_20180920_1447'),
        ('inventory', '0022_merge_20180920_1358'),
    ]

    operations = [
    ]
