# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-24 10:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_merge_20180920_1657'),
        ('inventory', '0024_auto_20180921_0948'),
    ]

    operations = [
    ]
