# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-27 05:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0025_auto_20180925_1838'),
        ('inventory', '0025_merge_20180924_1613'),
    ]

    operations = [
    ]
