# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-01 12:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0026_merge_20180927_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifycustomer',
            name='expire_at',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 1, 20, 0, tzinfo=utc)),
        ),
    ]
