# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentStatusResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tpn', models.CharField(max_length=200)),
                ('vendor_name', models.CharField(max_length=200)),
                ('vendor_id', models.CharField(max_length=200)),
                ('vendor_status', models.TextField()),
                ('is_payment_captured', models.BooleanField()),
                ('amount_captured', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
    ]
