# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-03 11:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_paymentstatusresponse_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('subtitle', models.CharField(blank=True, max_length=32, null=True)),
                ('method', models.CharField(max_length=32)),
                ('gateway_code', models.CharField(max_length=255)),
                ('gateway_code_level_1', models.CharField(blank=True, max_length=255, null=True)),
                ('priority', models.IntegerField(blank=True, null=True)),
                ('offers', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(max_length=100)),
                ('pin', models.CharField(blank=True, max_length=32, null=True)),
                ('expiry_month', models.CharField(blank=True, max_length=32, null=True)),
                ('expiry_year', models.CharField(blank=True, max_length=32, null=True)),
                ('brand', models.CharField(blank=True, max_length=32, null=True)),
                ('persist', models.BooleanField(default=True)),
            ],
            options={
                'managed': False,
            },
        ),
    ]
