# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimeElapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_id', models.IntegerField(blank=True, null=True)),
                ('increment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DateTimeField(blank=True, null=True)),
                ('out_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('processing_elapse', models.IntegerField(blank=True, null=True)),
                ('out_delivery_elapse', models.IntegerField(blank=True, null=True)),
                ('completed_elapse', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
