# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 10:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0002_ordertimeelapse_pending_elapse'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimeelapse',
            name='deliverytype',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
