# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 11:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sale_order', '0003_ordertimeelapse_deliverytype'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTimelapse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('increment_id', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('processing_time', models.DateTimeField(blank=True, null=True)),
                ('out_delivery_time', models.DateTimeField(blank=True, null=True)),
                ('completed_time', models.DateTimeField(blank=True, null=True)),
                ('pending_lapse', models.IntegerField(blank=True, null=True)),
                ('processing_lapse', models.IntegerField(blank=True, null=True)),
                ('out_delivery_lapse', models.IntegerField(blank=True, null=True)),
                ('deliverytype', models.IntegerField(blank=True, null=True)),
                ('driver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='OrderTimeElapse',
        ),
    ]
