# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-06 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0004_auto_20180424_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertimelapse',
            name='pending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
