# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-05-16 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale_order', '0006_auto_20180507_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertimeelapsed',
            name='increment_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
