# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-20 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='store_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
