# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-21 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='flock_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
    ]
