# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-09-25 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180921_0948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='store_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
